version: '3'
services:
# APP
  novosga:
    build: ./bin/novosga
    container_name: srv-novosga
    restart: always
    depends_on:
      - postgresql
    links: 
      - postgresql
    ports:
      - "8080:80"
      - "2020:2020"
    env_file:
    - ./.env/novosga-env
# DATABASE
  postgresql:
    build: ./bin/postgresql
    container_name: srv-postgresql
    restart: 'always'
    ports:
      - "5499:5432"
    env_file:
    - ./.env/postgresql-env