version: '3'

services:
# APP
  novosga:
    build: ./bin/novosga
    container_name: srv-novosga
    restart: always
    depends_on:
      - postgresql
    links: 
      - postgresql
    ports:
      - "8080:80"
      - "2020:2020"
    env_file:
    - ./.env/novosga-env

# DATABASE
  postgresql:
    build: ./bin/postgresql
    container_name: srv-postgresql
    restart: 'always'
    ports:
      - "5499:5432"
    env_file:
    - ./.env/postgresql-env

# PAINEL WEB build
  painelweb:
    build: ./bin/painelweb
    container_name: srv-painelweb
    depends_on:
      - novosga
    volumes: 
    - ./bin/painelweb/code/dist/web:/code/dist/web
    - ./bin/painelweb/code/build:/code/build
    # build html deployment
    command: yarn run build:web
    ## for build binary deployment
    # command: yarn run build

# PAINEL WEB NGINX
  painel-nginx:
    image: nginx:latest
    container_name: srv-painel-nginx
    restart: always
    depends_on:
      - painelweb
    links: 
      - novosga
    ports:
      - "8081:80"    
    volumes: 
    - ./bin/painelweb/code/dist/web:/var/www/html
    - ./bin/nginx/nginx.conf:/etc/nginx/nginx.conf