version: "3"

services:
  nginx:
    build: 
      context: ./bin/nginx
    container_name: 'srv-nginx'
    restart: 'always'
    ports:
      - "8080:80"
      - "8081:81"
    links: 
      - postgresql
      - php
    env_file:
    - ./.env/webserver-env
    volumes:
      - ./code:/code
      - ./conf/site.conf:/etc/nginx/conf.d/site.conf
  php:
    build: 
      context: ./bin/php
    container_name: 'srv-php'
    # ports:
    #   - "9000:9000"
    links: 
      - postgresql
    env_file:
    - ./.env/php-env
    volumes:
      - ./code:/code
  postgresql:
    build: ./bin/postgresql
    container_name: 'srv-postgresql'
    restart: 'always'
    ports:
      - "5499:5432"
    env_file:
    - ./.env/postgresql-env      
    # volumes: 
    #   - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
    #   - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql

##### testes 
  # webserver:
  #   build: 
  #     context: ./bin/webserver
  #   container_name: 'srv-webserver'
  #   restart: 'always'
  #   ports:
  #     - "8080:80"
  #   links: 
  #     - postgresql
  #     - php
  #   env_file:
  #   - ./.env/webserver-env
  #   volumes:
  #     - ./html:/var/www/html 