web:
    image: nginx:latest
    ports:
        - "8080:80"
        - "8081:81"
    volumes:
        - ./code:/code
        - ./conf/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code